## Pytorch

Pytorch is a ML and DL framework. to manipulate and process data and write ml algorithms

In [161]:
pip install torch 

Note: you may need to restart the kernel to use updated packages.



[notice] A new release of pip is available: 25.2 -> 26.0
[notice] To update, run: python.exe -m pip install --upgrade pip


In [162]:
import torch as th

th.__version__

'2.10.0+cpu'

Tensors are the fundamental building block of machine learning. their job is to represent data in a numerical way.

For example, you could represent an image as a tensor with shape [3, 224, 224] which would mean [colour_channels, height, width], as in the image has 3 colour channels (red, green, blue), a height of 224 pixels and a width of 224 pixels.

The first thing we're going to create is a scalar.

A scalar is a single number and in tensor-speak it's a zero dimension tensor.

In [163]:
# Scalar
scalar = th.tensor(7)
scalar

tensor(7)

In [164]:
# used to check the dimension of the tensor
scalar.ndim

0

In [165]:
# Get the Python number within a tensor 
scalar.item()

7

A vector is a single dimension tensor but can contain many numbers.

As in, you could have a vector [3, 2] to describe [bedrooms, bathrooms] in your house. Or you could have [3, 2, 2] to describe [bedrooms, bathrooms, car_parks] in your house.


In [166]:
# Vector
vector = th.tensor([7,7])
vector

tensor([7, 7])

In [167]:
# Check the number of dimension of vector
vector.ndim

1

In [168]:
#check the shape of the vector
vector.shape

torch.Size([2])

The above returns torch.Size([2]) which means our vector has a shape of [2]. This is because of the two elements we placed inside the square brackets ([7, 7]).

Let's now see a matrix.

In [169]:
# Matrix
MATRIX = th.tensor([[7, 8], 
                       [9, 10]])
MATRIX

tensor([[ 7,  8],
        [ 9, 10]])

In [170]:
# Check the number of dimensions
MATRIX.ndim

2

In [171]:
MATRIX.shape

torch.Size([2, 2])

In [172]:
# Tensor
TENSOR = th.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [173]:
# Check number of dimension for TENSOR
TENSOR.ndim

3

Why is the dimension = 3?

Because now you have THREE levels of nesting.

Let’s count them 👇

🔹 Level-by-level breakdown
Level 1 (outermost)
[
   [[1,2,3],
    [3,6,9],
    [2,4,5]]
]


➡️ This is one block (often called a batch)

Level 2 (rows)
[1,2,3]
[3,6,9]
[2,4,5]


➡️ These are rows

Level 3 (columns / values)
1, 2, 3, ...


➡️ Individual numbers (scalars)

In [174]:
TENSOR.shape

torch.Size([1, 3, 3])

## Random Tensors

As it is reare to create tensors by hand. a ml model often starts out with a large random tensors of numbers and adjusts these random numbers as it works though data to better represent it.

Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers...

In [175]:
# Create a random tensor of size (3,4)

random_tensor = th.rand(size=(3,4))
random_tensor, random_tensor.dtype

(tensor([[0.2666, 0.6274, 0.2696, 0.4414],
         [0.2969, 0.8317, 0.1053, 0.2695],
         [0.3588, 0.1994, 0.5472, 0.0062]]),
 torch.float32)

In [176]:
# Create a random tensor of size(224,224,3)

random_image_size_tensor =  th.rand(size=(224, 224, 3))
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([224, 224, 3]), 3)

In [177]:
# TO create a tensor of all zeros and ones

zeros = th.zeros(size= (3,4))
zeros, zeros.dtype

ones = th.zeros(size= (3,4))
ones, ones.dtype

(tensor([[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]),
 torch.float32)

## Creating a range and tensors like

Sometimes you might want a range of numbers, such as 1 to 10 or 0 to 100.

You can use torch.arange(start, end, step) to do so.

Where:

start = start of range (e.g. 0)
end = end of range (e.g. 10)
step = how many steps in between each value (e.g. 1)

In [178]:
# Use torch.arange(), torch.range() is deprecated 
zero_to_ten_deprecated = th.range(0, 10) # Note: this may return an error in the future

# Create a range of values 0 to 10
zero_to_ten = th.arange(start=0, end=10, step=1)
zero_to_ten

C:\Users\prave\AppData\Local\Temp\ipykernel_2380\138999720.py:2: UserWarning: torch.range is deprecated and will be removed in a future release because its behavior is inconsistent with Python's range builtin. Instead, use torch.arange, which produces values in [start, end).
  zero_to_ten_deprecated = th.range(0, 10) # Note: this may return an error in the future


tensor([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [179]:
# Can also create a tensor of zeroes similar to another tensor

ten_zeros = th.zeros_like(input = zero_to_ten)
# will have same shape

ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor Datatypes

There are different types of tensor datatypes available. Some are for CPU and some for GPU. Generally if you see torch.cuda anywhere, the tensor is being used for GPU (since Nvidia GPUs use a computing toolkit called CUDA).

The most common type (and generally the default) is torch.float32 or torch.float.

This is referred to as "32-bit floating point".

But there's also 16-bit floating point (torch.float16 or torch.half) and 64-bit floating point (torch.float64 or torch.double).

And to confuse things even more there's also 8-bit, 16-bit, 32-bit and 64-bit integers.

## precision in computing.

Precision is the amount of detail used to describe a number.

The higher the precision value (8, 16, 32), the more detail and hence data used to express a number.

This matters in deep learning and numerical computing because you're making so many operations, the more detail you have to calculate on, the more compute you have to use.

So lower precision datatypes are generally faster to compute on but sacrifice some performance on evaluation metrics like accuracy (faster to compute but less accurate).

In [180]:
# Default datatype for tensors is float32
float_32_tensor = th.tensor([3.0, 6.0, 9.0],
                               dtype=None, # defaults to None, which is torch.float32 or whatever datatype is passed
                               device=None, # defaults to None, which uses the default tensor type
                               requires_grad=False) # if True, operations performed on the tensor are recorded 

float_32_tensor.shape, float_32_tensor.dtype, float_32_tensor.device

(torch.Size([3]), torch.float32, device(type='cpu'))

In [181]:
float_16_tensor = th.tensor([3.0, 6.0, 9.0],
                               dtype=th.float16) # torch.half would also work

float_16_tensor.dtype

torch.float16

In [182]:
# lets create a tensor and get some info on it 

# Create a tensor
some_tensor = th.rand(3,4)

# lets get info
print(some_tensor)
print(f"Shape of tensor: {some_tensor.shape}")
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Device tensor is stored on: {some_tensor.device}") # will default to CPU

tensor([[0.9536, 0.6002, 0.0351, 0.6826],
        [0.3743, 0.5220, 0.1336, 0.9666],
        [0.9754, 0.8474, 0.8988, 0.1105]])
Shape of tensor: torch.Size([3, 4])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Manipulating tensors (Operations)

A model learns by investigating those tensors and performing a series of operations (could be 1,000,000s+) on tensors to create a representation of the patterns in the input data.

These operations are often a wonderful dance between:

Addition, Substraction, Multiplication (element-wise), Division, Matrix multiplication

In [183]:
# Lets do basic operations

tensor = th.tensor([1,2,3])

tensor + 10

tensor([11, 12, 13])

In [184]:
# multiply by 10
tensor * 10

tensor([10, 20, 30])

In [185]:
# tensors dont change unless reassigned
tensor

tensor([1, 2, 3])

In [186]:
# Subtract and reassign

tensor = tensor - 10
tensor

tensor([-9, -8, -7])

In [187]:
# add and resign
tensor = tensor + 10

PyTorch also has a bunch of built-in functions like torch.mul() (short for multiplication) and torch.add() to perform basic operations.

In [188]:
# can also use torch functions
th.multiply(tensor, 10)

tensor([10, 20, 30])

In [189]:
# Element-wise multiplication (each element multiplies its equivalent, index 0->0, 1->1, 2->2)
print(tensor, "*", tensor)
print("Equals:", tensor * tensor)

tensor([1, 2, 3]) * tensor([1, 2, 3])
Equals: tensor([1, 4, 9])



# Matrix multiplication
One of the most common operations in machine learning and deep learning algorithms (like neural networks) is matrix multiplication.

PyTorch implements matrix multiplication functionality in the torch.matmul() method.

The main two rules for matrix multiplication to remember are:

The inner dimensions must match:
(3, 2) @ (3, 2) won't work
(2, 3) @ (3, 2) will work
(3, 2) @ (2, 3) will work
The resulting matrix has the shape of the outer dimensions:
(2, 3) @ (3, 2) -> (2, 2)
(3, 2) @ (2, 3) -> (3, 3)
Note: "@" in Python is the symbol for matrix multiplication.

In [190]:
tensor = th.tensor([1,2,3])
tensor.shape

torch.Size([3])

In [191]:
# Element-wise matix multiplication
tensor * tensor

tensor([1, 4, 9])

In [192]:
# Matrix multiplication
th.matmul(tensor , tensor)

tensor(14)

In [193]:
# can alsor use '@' for matrix multiplication
tensor @ tensor

tensor(14)

In [194]:
%%time
# Matrix multiplication by hand 
# (avoid doing operations with for loops at all cost, they are computationally expensive)
value = 0
for i in range(len(tensor)):
  value += tensor[i] * tensor[i]
value

CPU times: total: 0 ns
Wall time: 634 μs


tensor(14)

In [195]:
%%time
th.matmul(tensor, tensor)

CPU times: total: 0 ns
Wall time: 61.5 μs


tensor(14)

In [196]:
# Shapes need to be in the right way  
tensor_A = th.tensor([[1, 2],
                         [3, 4],
                         [5, 6]], dtype=th.float32)

tensor_B = th.tensor([[7, 10],
                         [8, 11], 
                         [9, 12]], dtype=th.float32)

th.matmul(tensor_A, tensor_B) # (this will error)

RuntimeError: mat1 and mat2 shapes cannot be multiplied (3x2 and 3x2)

Why torch.matmul fails

Matrix multiplication follows this rule:

(m × n) · (n × p) → (m × p)

The inner dimensions must match.

What you have:
(3 × 2) · (3 × 2)
        ↑     ↑
        2 ≠ 3   ❌


The 2 columns of A do NOT match the 3 rows of B.

So PyTorch correctly throws an error.

In [197]:
# View tensor_A and tensor_B
print(tensor_A)
print(tensor_B)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7., 10.],
        [ 8., 11.],
        [ 9., 12.]])


In [198]:
# View tensor_A and tensor_B.T
print(tensor_A)
print(tensor_B.T)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
tensor([[ 7.,  8.,  9.],
        [10., 11., 12.]])


In [199]:
# The operation works when tensor_B is transposed
print(f"Original shapes: tensor_A = {tensor_A.shape}, tensor_B = {tensor_B.shape}\n")
print(f"New shapes: tensor_A = {tensor_A.shape} (same as above), tensor_B.T = {tensor_B.T.shape}\n")
print(f"Multiplying: {tensor_A.shape} * {tensor_B.T.shape} <- inner dimensions match\n")
print("Output:\n")
output = th.matmul(tensor_A, tensor_B.T)
print(output) 
print(f"\nOutput shape: {output.shape}")

Original shapes: tensor_A = torch.Size([3, 2]), tensor_B = torch.Size([3, 2])

New shapes: tensor_A = torch.Size([3, 2]) (same as above), tensor_B.T = torch.Size([2, 3])

Multiplying: torch.Size([3, 2]) * torch.Size([2, 3]) <- inner dimensions match

Output:

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Output shape: torch.Size([3, 3])


In [200]:
# torch.mm is a shortcut for matmul
th.mm(tensor_A, tensor_B.T)

tensor([[ 27.,  30.,  33.],
        [ 61.,  68.,  75.],
        [ 95., 106., 117.]])

Neural networks are full of matrix multiplications and dot products.

The torch.nn.Linear() module (we'll see this in action later on), also known as a feed-forward layer or fully connected layer, implements a matrix multiplication between an input x and a weights matrix A.

y = x.A^T + b 


Where:

x is the input to the layer (deep learning is a stack of layers like torch.nn.Linear() and others on top of each other).
A is the weights matrix created by the layer, this starts out as random numbers that get adjusted as a neural network learns to better represent patterns in the data (notice the "T", that's because the weights matrix gets transposed).
Note: You might also often see W or another letter like X used to showcase the weights matrix.
b is the bias term used to slightly offset the weights and inputs.
y is the output (a manipulation of the input in the hopes to discover patterns in it).

In [201]:
# Since the linear layer starts with a random weights matrix, let's make it reproducible (more on this later)
th.manual_seed(42)
# This uses matrix multiplication
linear = th.nn.Linear(in_features=2, # in_features = matches inner dimension of input 
                         out_features=6) # out_features = describes outer value 
x = tensor_A
output = linear(x)
print(f"Input shape: {x.shape}\n")
print(f"Output:\n{output}\n\nOutput shape: {output.shape}")

Input shape: torch.Size([3, 2])

Output:
tensor([[2.2368, 1.2292, 0.4714, 0.3864, 0.1309, 0.9838],
        [4.4919, 2.1970, 0.4469, 0.5285, 0.3401, 2.4777],
        [6.7469, 3.1648, 0.4224, 0.6705, 0.5493, 3.9716]],
       grad_fn=<AddmmBackward0>)

Output shape: torch.Size([3, 6])


In [207]:
import torch as th
x = th.arange(0, 100, 10)
x


tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [209]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(th.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450
